routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/profile', 'ProfileController');

Route::resource('/pertanyaan', 'PertanyaanController');

Route::resource('/jawaban', 'JawabanController');

Route::resource('/materi', 'MateriController');

Route::get('/index/all', 'PertanyaanController@showAll');

Route::get('/filePertanyaan/{file}', 'PertanyaanController@download' );

Route::get('/fileJawaban/{file}', 'JawabanController@download' );

Route::get('/likePertanyaan/{id}', 'ProfileController@likePertanyaan');

Route::get('/dislikePertanyaan/{id}', 'ProfileController@dislikePertanyaan');

Route::get('/likeJawaban/{id}', 'ProfileController@likeJawaban');

Route::get('/dislikeJawaban/{id}', 'ProfileController@dislikeJawaban');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/tampilan/index.blade.php
@extends('layouts.master')

@section('title')
    Home
@endsection

@section('content')
{{-- Modal Trigger --}}
  <div class="row">
    <div class="col-md-6">
      <button type="button" class="btn btn-primary btn-user btn-block mb-3" data-toggle="modal" data-target="#modal_tugas">
        Buat Pertanyaan Baru
      </button>
    </div>

    <div class="col-md-6">
      <a class="btn btn-primary mb-3 btn-user btn-block" href="/index/all" role="button">Lihat List Pertanyaan</a>
    </div>
  </div>
    
  @if (session("success"))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <h4>{{session("success")}}</h4>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    </div>
  @endif

  {{-- <div class="row">
    <div class="col-lg-4">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Contoh List Tugas</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink" style="">
                        <div class="dropdown-header">Setting:</div>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#modal_tugas_edit">Edit Pertanyaan</a>
                        <a class="dropdown-item" href="/index/show">Show</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item text-danger" href="#">Delete Pertanyaan</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <p>Nama Materi: bla bla bla</p>
                <p>Tugas: buatlah diagram flow terus di kumpulkan dalam bentuk gambar</p>
                <div class="dropdown-divider"></div>
                <div class="d-flex justify-content-between">
                  <a class="like" href="#">100&nbsp;<i class="far fa-thumbs-up"></i></a>
                  <a class="dislike" href="#">50&nbsp;<i class="far fa-thumbs-down"></i></a>
                </div>
            </div> --}}
  {{-- <button type="button" class="btn btn-primary btn-user btn-block mb-3" data-toggle="modal" data-target="#modal_tugas">
    Buat Pertanyaan Baru
  </button> --}}

<div class="row">
  @forelse ($listPertanyaan as $key => $isi)
  <div class="col-lg-4">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">{{$isi->judul_pertanyaan}}</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink" style="">
                    <div class="dropdown-header">Setting:</div>
                    {{-- <a class="dropdown-item" href="{{route('pertanyaan.show', ['pertanyaan'=>$isi->id_pertanyaan])}}">Show</a> --}}
                    <a class="dropdown-item" href="/pertanyaan/{{$isi->id_pertanyaan}}/edit" data-toggle="modal" data-target="#modal_tugas_edit{{$isi->id_pertanyaan}}">Edit</a>
                    <a class="dropdown-item" href="{{route('pertanyaan.show', ['pertanyaan'=>$isi->id_pertanyaan])}}">Show</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="/pertanyaan/{{$isi->id_pertanyaan}}" data-toggle="modal" data-target="#modal_tugas_hapus{{$isi->id_pertanyaan}}">Delete</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            <p>Keterangan: {{$isi->isi_pertanyaan}}</p>
            <p>File: {{old('default', $isi->file_pertanyaan ?? 'Tidak ada Attachement')}}</p>
        </div>
    </div>
</div>
  @empty
      <div class="col-lg-12">
        <h3>Tidak ada pertanyaan yang dibuat</h3>
      </div>
  @endforelse
    
</div>


{{-- Modal untuk buat pertanyaan--}}
<div class="modal fade" id="modal_tugas" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg"  role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Pertanyaan Baru</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form role="form" action="/pertanyaan" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
              <label for="judul_pertanyaan">Judul Pertanyaan</label>
              <input type="text" class="form-control"
                    id="judul_pertanyaan" name="judul_pertanyaan"
                    placeholder="Judul Pertanyaan">
            </div>

            <div class="form-group">
              <label for="isi_pertanyaan">Isi Pertanyaan</label>
                <input type="text" class="form-control"
                    id="isi_pertanyaan" name="isi_pertanyaan"
                    placeholder="Keterangan Pertanyaan">
            </div>

            <div class="form-group">
              <label for="file">Upload File (Jika Diperlukan)</label>
              <input type="file" class="dropify" data-height="300" id="input_file" name="input_file">
            </div>

            <div class="form-group">
              <label for="materi">Materi Terkait</label>
              <input type="text" class="form-control"
                  id="materi" name="materi"
                  placeholder="Pisahkan dengan tanda koma jika lebih dari 1 materi. Cth: matematika,fisika,kimia">
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
          </form>
        </div>
        
      </div>
    </div>
</div>


{{-- Modal untuk edit tugas --}}
@forelse ($listPertanyaan as $key => $isi)
  <div class="modal fade" id="modal_tugas_edit{{$isi->id_pertanyaan}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Edit Pertanyaan</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="/pertanyaan/{{$isi->id_pertanyaan}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
              <label for="judul_pertanyaan">Judul Pertanyaan</label>
              <input type="text" class="form-control"
              id="judul_pertanyaan" name="judul_pertanyaan"
              placeholder="Judul Pertanyaan" value = "{{old('judul_pertanyaan', $isi->judul_pertanyaan ?? '')}}">
            </div>

            <div class="form-group">
              <label for="judul_pertanyaan">Isi Pertanyaan</label>
              <input type="text" class="form-control"
              id="isi_pertanyaan" name="isi_pertanyaan"
              placeholder="Isi Pertanyaan" value = "{{old('judul_pertanyaan', $isi->isi_pertanyaan ?? '')}}">
            </div>

            <div class="form-group">
              <label for="judul_pertanyaan">Upload File (Jika Diperlukan) </label>
              <div class="custom-file">
                  <input type="file" class="dropify" data-height="100" id="input_file" name="input_file" value = "{{old('judul_pertanyaan', $isi->input_file ?? '')}}">
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
          </form>
        </div>
        
      </div>
    </div>
  </div>
@empty
    
@endforelse

{{-- Modal untuk Delete tugas --}}
@forelse ($listPertanyaan as $key => $isi)
  <div class="modal fade" id="modal_tugas_hapus{{$isi->id_pertanyaan}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Hapus Pertanyaan</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="/pertanyaan/{{$isi->id_pertanyaan}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('DELETE')
            <div class="form-group">
              <h2>Apakah anda yakin ingin menghapus pertanyaan ini?</h2>
              <h3>Judul Pertanyaan: {{$isi->judul_pertanyaan}} </h3>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                <form action="/pertanyaan/{{$isi->id_pertanyaan}}" method="POST">
                  @csrf
                  @method('DELETE')        
                  <input type="submit" name="delete" id="delete" value='Hapus' class="btn btn-danger btn-sm">
                </form>
              </div>
          </form>
        </div>
        
      </div>
    </div>
  </div>
@empty
    
@endforelse

@endsection

@push('dropify')
<script src="{{ asset('dropify/dist/js/dropify.js' )}}"></script>
<script type="text/javascript">
        $(document).ready(function(){
            $('.dropify').dropify();
        });
</script>
@endpush

resources/views/tampilan/index_semua.blade.php
@extends('layouts.master')

@section('title')
    List Pertanyaan
@endsection

@section('content')
    <div class="row">
        <div class="col-md-6">
            <button type="button" class="btn btn-primary btn-user btn-block mb-3" data-toggle="modal" data-target="#modal_tugas">
                Buat Pertanyaan Baru
            </button>
        </div>

        <div class="col-md-6">
            <a class="btn btn-primary mb-3 btn-user btn-block" href="/pertanyaan" role="button">Pertanyaan oleh {{Auth::user()->name}} </a>
        </div>
    </div>

    <div class="row">
      @forelse ($listPertanyaan as $key => $isi)
          <div class="col-lg-4">
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary"><a href="{{route('jawaban.show', ['jawaban'=>$isi->id_pertanyaan])}}">{{$isi->judul_pertanyaan}}</a></h6>
              </div>

              <div class="card-body">
                <p>Keterangan: {{$isi->isi_pertanyaan}}</p>
                <p>File: {{old('default', $isi->file_pertanyaan ?? 'Tidak ada Attachement')}}</p>
                <p>Pembuat Pertanyaan: {{$isi->PertanyaanMilik->name}}</p>
                {{-- <p><a href="{{route('pertanyaan.show', ['pertanyaan'=>$isi->id_pertanyaan])}}" class="btn btn-primary" type="button">Detail Pertanyaan</a></p> --}}
              </div>
          </div>
        </div>
      @empty
        <div class="col-lg-12">
          <h3>Tidak ada pertanyaan yang dibuat</h3>
        </div>
      @endforelse
    </div>

    {{-- Modal Buat Pertanyaan --}}
    <div class="modal fade" id="modal_tugas" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg"  role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalCenterTitle">Pertanyaan Baru</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form role="form" action="/pertanyaan" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                  <label for="judul_pertanyaan">Judul Pertanyaan</label>
                  <input type="text" class="form-control"
                        id="judul_pertanyaan" name="judul_pertanyaan"
                        placeholder="Judul Pertanyaan">
                </div>
    
                <div class="form-group">
                  <label for="isi_pertanyaan">Isi Pertanyaan</label>
                    <input type="text" class="form-control"
                        id="isi_pertanyaan" name="isi_pertanyaan"
                        placeholder="Keterangan Pertanyaan">
                </div>
    
                <div class="form-group">
                  <label for="file">Upload File (Jika Diperlukan)</label>
                  <input type="file" class="dropify" data-height="300" id="input_file" name="input_file">
                </div>
    
                <div class="form-group">
                  <label for="materi">Materi Terkait</label>
                  <input type="text" class="form-control"
                      id="materi" name="materi"
                      placeholder="Pisahkan dengan tanda koma jika lebih dari 1 materi. Cth: matematika,fisika,kimia">
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                  </div>
              </form>
            </div>
            
          </div>
        </div>
    </div>
@endsection

@push('dropify')
    <script src="{{ asset('dropify/dist/js/dropify.js' )}}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.dropify').dropify();
        });
    </script>
@endpush

resources/views/tampilan/show.blade.php
@extends('layouts.master')

@section('title')
    Show
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Show Pertanyaan & Jawaban</h6>
        </div>

        <div class="card-body">
            <h6>Judul Pertanyaan: {{$show->judul_pertanyaan}} </h6>
            <h6>Keterangan Pertanyaan: {{$show->isi_pertanyaan}} </h6>
            <h6>File Pertanyaan: <a href="/filePertanyaan/{{$show->file_pertanyaan}}">{{$show->file_pertanyaan}}</a>  </h6>
            <h6>Materi Terkait:  
                @foreach ($show->MateriTerkait as $materi)
                    <button class="btn btn-info btn-sm" type="button"> {{$materi->nama_materi}} </button>
                @endforeach
            </h6>
            <p>
                <a class="btn btn-primary" href="/pertanyaan" role="button">Kembali ke halaman sebelumnya</a>
            </p>

            <table class="table table-bordered">
                <thead>
                    <tr class="text-center">
                        <th style="width: 10px">No</th>
                        <th>Pemberi Jawaban</th>
                        <th>Keterangan Jawaban</th>
                        <th>File Jawaban</th>
                    </tr>
                </thead>

                <tbody>
                    @forelse ($show->DaftarJawaban as $key => $jawaban)
                    <tr>
                        <td> {{$key+1}}</td>
                        <td> {{$jawaban->PemberiJawaban->name}} </td>
                        <td> {!! $jawaban->isi_jawaban !!} </td>
                        <td> <a href="/fileJawaban/{{$jawaban->file_jawaban}}"> {{$jawaban->file_jawaban}} </a> </td>
                    </tr>
                    @empty
                        <td colspan="4" align="center">Belum ada yang menjawab pertanyaan anda</td>       
                    @endforelse
                    
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/tampilan/show_jawab.blade.php
@extends('layouts.master')

@section('title')
    Show
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Pertanyaan dari {{$show->PertanyaanMilik->name}} </h6>
        </div>

        <div class="card-body">
            <h6>Judul Pertanyaan: {{$show->judul_pertanyaan}} 
                <a class="btn-success btn-sm fa-pull-right" href="/likePertanyaan/{{ $show->id_pertanyaan }}">Like! <i class="far fa-thumbs-up"> {{$like}}</i></a>
            </h6> 
            <h6>Keterangan Pertanyaan: {{$show->isi_pertanyaan}} 
            </h6>
            <h6>File Pertanyaan: <a href="/filePertanyaan/{{$show->file_pertanyaan}}">{{$show->file_pertanyaan}}</a>
                <a class="btn-danger btn-sm fa-pull-right" href="/dislikePertanyaan/{{ $show->id_pertanyaan }}">Dislike! <i class="far fa-thumbs-down"> {{$dislike}}</i></a>
            </h6>
            <h6>Materi Terkait:  
                @foreach ($show->MateriTerkait as $materi)
                    <button class="btn btn-info btn-sm" type="button"> {{$materi->nama_materi}} </button>
                @endforeach
            </h6>
            <p>
                <a class="btn btn-primary" href="/index/all" role="button">Kembali ke halaman sebelumnya</a>
                <a class="btn btn-primary fa-pull-right" href="/pertanyaan" role="button" data-toggle="modal" data-target="#modal_jawab">Berikan Jawaban Anda</a>
            </p>

            <table class="table table-bordered">
                <thead>
                    <tr class="text-center">
                        <th style="width: 10px">No</th>
                        <th>Pemberi Jawaban</th>
                        <th>Keterangan Jawaban</th>
                        <th>File Jawaban</th>
                        <th style="width: 200px">Actions</th>
                    </tr>
                </thead>

                <tbody>
                    @forelse ($show->DaftarJawaban as $key => $jawaban)
                    <tr>
                        <td> {{$key+1}}</td>
                        <td> {{$jawaban->PemberiJawaban->name}} </td>
                        <td> {!! $jawaban->isi_jawaban !!} </td>
                        <td> <a href="/fileJawaban/{{$jawaban->file_jawaban}}"> {{$jawaban->file_jawaban}} </a> </td>
                        <td>
                          <a class="btn-success btn-sm btn-block text-center" href="/likeJawaban/{{ $jawaban->id_jawaban }}">Like! <i class="far fa-thumbs-up"> {{$jawaban->jml_like}}</i></a>
                          <a class="btn-danger btn-sm btn-block text-center" href="/dislikeJawaban/{{ $jawaban->id_jawaban }}">Dislike! <i class="far fa-thumbs-down"> {{$jawaban->jml_dislike}}</i></a>
                        </td>
                    </tr>
                    @empty
                        <td colspan="5" align="center">Belum ada yang menjawab pertanyaan anda</td>       
                    @endforelse
                    
                </tbody>
            </table>
            
        </div>
    </div>

{{-- Modal untuk jawab pertanyaan--}}
<div class="modal fade" id="modal_jawab" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg"  role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Jawaban Baru</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form role="form" action="/jawaban" method="POST" enctype="multipart/form-data">
            @csrf

            <input type="hidden" name="id_pertanyaan" id="id_pertanyaan" value="{{$show->id_pertanyaan}}">

            <div class="form-group">
                <label for="isi_jawaban">Isi Jawaban</label>
                <textarea name="isi_jawaban" id="isi_jawaban" class="form-control my-editor">{!! old('isi_jawaban', $isi_jawaban ?? '') !!}</textarea>
            </div>

            <div class="form-group">
              <label for="file">Upload File (Jika Diperlukan)</label>
              <input type="file" class="dropify" data-height="300" id="input_file" name="input_file">
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
          </form>
        </div>
        
      </div>
    </div>
</div>

@endsection

@push('dropify')
<script src="{{ asset('dropify/dist/js/dropify.js' )}}"></script>
<script type="text/javascript">
        $(document).ready(function(){
            $('.dropify').dropify();
        });
</script>
@endpush

@push('file_manager')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

    <script>
        var editor_config = {
          path_absolute : "/",
          selector: "textarea.my-editor",
          plugins: [
            "advlist autolink lists link image charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code fullscreen",
            "insertdatetime media nonbreaking save table contextmenu directionality",
            "emoticons template paste textcolor colorpicker textpattern"
          ],
          toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
          relative_urls: false,
          file_browser_callback : function(field_name, url, type, win) {
            var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
            var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;
      
            var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
            if (type == 'image') {
              cmsURL = cmsURL + "&type=Images";
            } else {
              cmsURL = cmsURL + "&type=Files";
            }
      
            tinyMCE.activeEditor.windowManager.open({
              file : cmsURL,
              title : 'Filemanager',
              width : x * 0.8,
              height : y * 0.8,
              resizable : "yes",
              close_previous : "no"
            });
          }
        };
      
        tinymce.init(editor_config);
    </script>
@endpush